name       : gtypist
version    : 2.9.5
release    : 1
source     :
    - https://ftp.gnu.org/gnu/gtypist/gtypist-2.9.5.tar.xz : c13af40b12479f8219ffa6c66020618c0ce305ad305590fde02d2c20eb9cf977
license    : GPL-3.0
component  : office
summary    : A universal typing tutor
description: |
    GNU Typist is a universal typing tutor. You can learn correct typing and improve your skills by practising its exercises on a regular basis.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
